#### Operaciones matriciales

In [1]:
# Cargo el módulo de numpy
#-------------------------
import numpy as np

In [2]:
# Armo mi matriz de prueba
#-------------------------
mat=np.array([[1,2],[3,4],[0,1]], dtype=np.float64)
print(mat)

[[1. 2.]
 [3. 4.]
 [0. 1.]]


#### Ejercicio 1: Definición de normas

Trabajando siempre en modo vectorizado

In [3]:
# Defino las normas
#------------------
def norm_l0(m):
    mask = m > 0
    return np.sum(mask)

def norm_l1(m):
    abs_m=np.abs(m)
    return np.sum(abs_m,axis=1) # Suma por filas (con axis=0 sería por columnas)

def norm_l2(m):
    sqr_m=np.square(m)
    return np.sqrt(np.sum(sqr_m,axis=1))

def norm_inf(m):
    return np.max(m, axis=1)

In [7]:
norm0=norm_l0(mat)
print('Norma 0: {}'.format(norm0))

norm1=norm_l1(mat)
print('Norma 1: {}'.format(norm1))

norm2=norm_l2(mat)
print('Norma 2: {}'.format(norm2))

norminf=norm_inf(mat)
print('Norma infinito: {}'.format(norminf))

Norma 0: 5
Norma 1: [3. 7. 1.]
Norma 2: [2.23606798 5.         1.        ]
Norma infinito: [2. 4. 1.]


#### Ejercicio 2: Sorting

Ordenar según la norma dos obtenida en el ejercicio anterior

In [6]:
# Sorting: Ordenamos segun la norma 2
id_ord = np.argsort(norm2) # ordena y devuelve los índices de los valores ordenados
print(id_ord)

mat_ord=mat[id_ord]
print(mat_ord)

[2 0 1]
[[0. 1.]
 [1. 2.]
 [3. 4.]]


#### Definimos los tests de prueba

In [4]:
from unittest import TestCase
import numpy as np
import math

#from clase_1.norm import norm_l0

class NormTestCase(TestCase):

    def test_norm_l0(self):
        a = np.array([[1,2,3,4],[5,6,7,8]])
        expected = 6
        result = norm_l0(a)
        self.assertTrue(expected, result)

        a = np.array([[1,0,0,4],[5,6,0,8]])
        expected = 5
        result = norm_l0(a)
        self.assertTrue(expected, result)
        
    def test_norm_l1(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        expected = np.array([10, 26])
        result = norm_l1(a)
        np.testing.assert_equal(expected, result)
        
        a = np.array([[-1, -2, -3, -4], [-5, -6, -7, -8]])
        expected = np.array([10, 26])
        result = norm_l1(a)
        np.testing.assert_equal(expected, result)
        
    def test_norm_l2(self):
        a = np.array([[1, 2], [3, 4]])
        expected = np.array([math.sqrt(5), math.sqrt(25)])
        result = norm_l2(a)
        np.testing.assert_allclose(expected, result)
        
    def test_norm_inf(self):
        a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
        expected = np.array([4, 8])
        result = norm_inf(a)
        np.testing.assert_equal(expected, result)

In [7]:
# Creo un objeto de prueba y corro los tests

test_obj = NormTestCase()

test_obj.test_norm_l0()
test_obj.test_norm_l1()
test_obj.test_norm_l2()
test_obj.test_norm_inf()